src/cloudlabs/forms/add_host.py
from flask import g
from flask_wtf import FlaskForm
from wtforms.fields import (
    IntegerField,
    PasswordField,
    SelectField,
    StringField,
    TextAreaField
)
import wtforms.validators as v

from ..models import Host, SshKey


class AddHostForm(FlaskForm):
    """Form for adding a new virtual host."""

    label = StringField(
        'Label',
        description='A short label for you to identify this host easily',
        validators=[v.Length(min=2, max=Host.label.type.length)])

    description = TextAreaField(
        'Description',
        description='A longer description of the host, purely for your own '
                    'benefit',
        validators=[v.Optional()])

    base_name = StringField(
        'URL',
        description='The canonical DNS name for this host, which must be '
                    'globally unique. Note that the .cloudlabs.rc.ucl.ac.uk '
                    'suffix will be added automatically, and should not be '
                    'included here.',
        validators=[v.Length(min=1, max=Host.dns_name.type.length)])
    # TODO adapt max length to exclude suffixes/randomisation?

    vm_size = SelectField(
        'VM size',
        description='Specifications of new host',
        choices=[('Standard_A1_v2', '1 core, 2GB RAM'),
                 ('Standard_A4_v2', '4 cores, 8GB RAM'),
                 ('Standard_A4m_v2', '4 cores, 32GB RAM')])

    admin_username = StringField(
        'Admin username',
        description='Username of the admin user to be created on the new host',
        validators=[v.Length(min=1, max=Host.admin_username.type.length)])

    auth_type = SelectField(
        'Authentication type',
        description='How the admin user should be authenticated when logging '
                    'in via SSH',
        choices=[('SSH', 'SSH public key'), ('Password', 'Password')])

    admin_ssh_key = SelectField(
        'SSH public key',
        description='Which of your pre-configured SSH public keys to use for '
                    'logging in.'
        ' Set up further keys by visiting your profile page.',
        coerce=int)

    admin_password = PasswordField(
        'Admin password',
        description='Password to use for the admin user on this host',
        validators=[v.Optional(), v.Length(min=12,
                                           max=Host.admin_password.type.length
                                           )])

    git_repo = StringField(
        'Git repository',
        description='Location of the git repository to clone on the new host.'
        ' It is assumed to contain a Dockerfile that will be built,'
        ' although this can be customised.',
        validators=[v.Length(min=1, max=Host.git_repo.type.length)])

    port = IntegerField(
        'Port',
        description='Which port the web application should be exposed on.'
        ' This is used to generate our default installation script,'
        ' which can be customised if needed.',
        default=80,
        validators=[v.NumberRange(min=1, max=65535)])

    def validate_label(form, field):
        """Check a user doesn't duplicate labels."""
        label = field.data.strip()
        if Host.query.filter_by(user_id=g.user.id, label=label).count() > 0:
            raise v.ValidationError('You must choose a unique label for each '
                                    'host')

    def validate_dns_name(form, field):
        """DNS names must be globally unique."""
        dns_name = field.data.strip()
        if Host.query.filter_by(dns_name=dns_name).count() > 0:
            raise v.ValidationError('The URL {} has already '
                                    'been taken'.format(dns_name))

    def validate_admin_ssh_key(form, field):
        """The user must pick one of their keys."""
        key_id = field.data
        if key_id and SshKey.query.filter_by(user_id=g.user.id,
                                             id=key_id).count() == 0:
            raise v.ValidationError(
                        'You must select one of your pre-configured SSH keys')

src/cloudlabs/forms/add_key.py
from flask import g
from flask_wtf import FlaskForm
from wtforms.fields import StringField, TextAreaField
import wtforms.validators as v

from ..models import SshKey


class AddKeyForm(FlaskForm):
    """Form for adding a new SSH public key."""
    label = StringField(
        'Label',
        description='A label to allow you to identify this key',
        validators=[v.Length(min=2, max=SshKey.label.type.length)])
    public_key = TextAreaField(
        'Public key',
        description='The public key itself, e.g. copied from '
                    '~/.ssh/id_rsa.pub',
        validators=[v.DataRequired()])

    def validate_label(form, field):
        """Check a user doesn't duplicate labels."""
        existing_labels = [key.label for key in g.user.ssh_keys]
        if field.data.strip() in existing_labels:
            raise v.ValidationError(
                                'You must choose a unique label for each key')

src/cloudlabs/views.py
import logging

from flask import (
    abort,
    Blueprint,
    flash,
    g,
    redirect,
    render_template,
    url_for,
)
from .forms.add_key import AddKeyForm
from .models import SshKey
from .utils import login_required


logger = logging.getLogger("cloudlabs.admin")

blueprint = Blueprint('main', __name__)


@blueprint.route('/')
def index():
    return render_template('index.html')


@blueprint.route('/profile')
@login_required
def profile():
    return render_template('profile.html')


@blueprint.route('/data_info')
def data_info():
    """Show a confirmation page with information on data-related limitations."""
    return render_template('data_info.html')


@blueprint.route('/help')
def help():
    """Show a help page with general information about CloudLabs."""
    return render_template('help.html')


@blueprint.route('/keys/add', methods=('GET', 'POST'))
@login_required
def add_key():
    form = AddKeyForm()
    if form.validate_on_submit():
        SshKey.create(
            user_id=g.user.id,
            label=form.label.data.strip(),
            public_key=form.public_key.data.strip())
        flash('SSH key "{}" added'.format(form.label.data), 'success')
        logger.info("%s added new key %s", g.user.ucl_id, form.label.data)
        return redirect(url_for('main.profile'))
    return render_template('add_key.html', form=form)


@blueprint.route('/keys/<int:id>/delete')
@login_required
def delete_key(id):
    key = SshKey.query.get_or_404(id)
    if key.user is not g.user:
        abort(404)
    label = key.label
    key.delete()
    logger.info("%s deleted key %s", g.user.ucl_id, label)
    flash('SSH key "{}" deleted'.format(label), 'success')
    return redirect(url_for('main.profile'))

src/cloudlabs/templates/add_host.html
{% extends "base.html" %}
{% from "includes/_form_helpers.html" import render_field %}


{% block breadcrumb_links %}
  {{ super() }}
  <li class="breadcrumb__item">New machine</li>
{% endblock breadcrumb_links %}


{% block content %}
  <h1>Add new virtual machine for {{ user['name'] }}</h1>

  <form method="POST" action="{{ url_for('host.add') }}">
    {{ form.csrf_token }}
    <fieldset>
      <legend>Basic settings</legend>
      {{ render_field(form.label) }}
      {{ render_field(form.description) }}
      {{ render_field(form.base_name) }}
      {{ render_field(form.vm_size) }}
    </fieldset>
    <fieldset>
      <legend>Admin account details</legend>
      {{ render_field(form.admin_username) }}
      {{ render_field(form.auth_type) }}
      <div id="div__ssh_key">
        {{ render_field(form.admin_ssh_key) }}
      </div>
      <div id="div__password">
        {{ render_field(form.admin_password) }}
      </div>
    </fieldset>
    <fieldset>
      <legend>Machine setup</legend>
      {{ render_field(form.git_repo) }}
      {{ render_field(form.port) }}
    </fieldset>
    <input class="btn" type="submit" name="action" value="Add with default setup script"/>
    <input class="btn" type="submit" name="action" value="Customise setup script"/>
  </form>
{% endblock content %}


{% block scripts %}
  {{ super() }}
  {# TODO: Put this in a static JS file loaded with require() and using jQuery #}
  <script>
    var input__auth_type = document.getElementById('auth_type'),
        div__ssh_key = document.getElementById('div__ssh_key'),
        div__password = document.getElementById('div__password');
    input__auth_type.onchange = function () {
      var choice = input__auth_type.options[input__auth_type.selectedIndex].value;
      if (choice == 'SSH') {
        div__ssh_key.style.display = 'block';
        div__password.style.display = 'none';
      } else {
        div__ssh_key.style.display = 'none';
        div__password.style.display = 'block';
      }
    };
    input__auth_type.onchange();
  </script>
{% endblock scripts %}

src/cloudlabs/templates/add_key.html
{% extends "base.html" %}
{% from "includes/_form_helpers.html" import render_field %}


{% block breadcrumb_links %}
  {{ super() }}
  <li class="breadcrumb__item"><a href="{{ url_for('main.profile') }}">Profile</a></li>
  <li class="breadcrumb__item">Add SSH key</li>
{% endblock breadcrumb_links %}


{% block content %}
  <h1>Add new SSH public key for {{ user['name'] }}</h1>

  <form method="POST" action="{{ url_for('main.add_key') }}">
    {{ form.csrf_token }}
    {{ render_field(form.label) }}
    {{ render_field(form.public_key) }}
    <input class="btn" type="submit" value="Add" />
  </form>

{% endblock content %}

src/cloudlabs/templates/base.html
{% extends "indigo/base.html" %}


{% block page_title %}Self-serve Web Hosting for Research Applications{% endblock page_title %}


{% block body_class %}
  {% if user %}logged-in{% else %}logged-out{% endif %}
  {{ super() }}
{% endblock body_class %}


{% block styles %}
  {{ super() }}
  <link href="//cdn.ucl.ac.uk/skins/UCLIndigoSkin/default-theme/css/brightgreen.min.css" media="screen, projection" rel="stylesheet" type="text/css" />
  <style>
    /* TODO: Put this in a static file! */
    .login-state {
      position: absolute;
      top: 1em;
      right: 35px;
    }
    img.action {
      cursor: pointer;
      height: 1.2em;
      margin: 0em 0.1em;
      vertical-align: middle;
    }
    img.inline {
      height: 0.9em;
      margin: 0em 0.5em;
      vertical-align: middle;
    }
    label {
      display: inline;
    }
  </style>
{% endblock styles %}


{% block nav_top_inner %}
  {{ super() }}
  {% include "includes/_login_state.html" %}
{% endblock nav_top_inner %}


{% block nav_mobile_inner %}
  {{ super() }}
  {% include "includes/_login_state.html" %}
{% endblock nav_mobile_inner %}


{% block breadcrumb_links %}
  <li class="breadcrumb__item"><a href="https://www.ucl.ac.uk/">UCL Home</a></li>
  <li class="breadcrumb__item"><a href="http://www.ucl.ac.uk/research-it-services">Research IT Services</a></li>
  <li class="breadcrumb__item"><a href="{{ url_for('main.index') }}">Self-serve Web Hosting for Research Applications</a></li>
{% endblock breadcrumb_links %}


{% block content_body %}
  {% include "includes/_messages.html" %}
  {{ super() }}
{% endblock %}

src/cloudlabs/templates/data_info.html
{% extends "base.html" %}

{% block content %}

<p>This portal allows you to create virtual machines (hosts) for a number of
purposes. Before you continue, we need to stress that <strong>these machines
cannot be used to host personal or sensitive data</strong>.

<p>To make sure that our users comply with this, we would like to ask you to take a
moment to consider the following questions about your intended use of the
service:<br>
(in this case, "<em>the project</em>" refers to the code you run from the created
host and any data stored there or transferred through it)

<ul>
  <li>Will the project involve the collection of new information about individuals?</li>
  <li>Will the project compel individuals to provide information about themselves?</li>
  <li>Will information about individuals be disclosed to organisations or people who have not previously had routine access to the information?</li>
  <li>Are you using information about individuals for a purpose it is not currently used for, or in a way it is not currently used?</li>
  <li>Does the project involve you using new technology that might be perceived as being privacy intrusive? For example, the use of biometrics or facial recognition.</li>
  <li>Will the project result in you making decisions or taking action against individuals in ways that can have a significant impact on them?</li>
  <li>Is the information about individuals of a kind particularly likely to raise privacy concerns or expectations? For example, health records, criminal records or other information that people would consider to be private.</li>
  <li>Will the project require you to contact individuals in ways that they may find intrusive?</li>
</ul>

<p>If you answer "yes" to any of the above, we may unfortunately be unable to
host your application.
If you are concerned that your use case does not comply with these restrictions
or you need more information, please feel free to contact us by
<a href="mailto:rc-softdev@ucl.ac.uk">email</a>.

<p>Note that UCL provides specialised solutions for storing and handling personal
data, such as the <a href="https://www.ucl.ac.uk/isd/itforslms/services/handling-sens-data/tech-soln">
Data Safe Haven</a>, which may be more suitable for your purposes.
The UCL Information Security Group also have an
<a href="https://opinio.ucl.ac.uk/s?s=45808">online tool</a> to help you better
understand the risks associated with your data set.

<p>By proceeding, you indicate that you understand and agree with these constraints.

<p><a class="btn" href="{{ url_for('host.add') }}">I understand and want to create a host</a>
{% endblock content %}

src/cloudlabs/templates/deploy_log.html
{% extends "base.html" %}


{% block meta %}
  {{ super() }}
  {% if host.status in [HostStatus.deploying, HostStatus.destroying] %}
    <meta http-equiv="refresh" content="5">
  {% endif %}
{% endblock meta %}


{% block breadcrumb_links %}
  {{ super() }}
  <li class="breadcrumb__item">{{ host.label }}</li>
{% endblock breadcrumb_links %}


{% block content %}
  <h1>Deployment log for <a href="{{ url_for('host.info', id=host.id) }}">{{ host.label }}</a></h1>

  {% if host.status == HostStatus.error %}
    <p>Deploying this host failed. See the log below for more information.</p>
  {% elif host.status == HostStatus.destroying %}
    <p>This host is currently being destroyed.</p>
  {% elif host.status == HostStatus.defining %}
    <p>This host is not currently deployed to the cloud.</p>
  {% elif host.status != HostStatus.deploying %}
    <p>
    This host has been successfully deployed.
    {% if host.status == HostStatus.running %}
      You can view the live application at <a href="{{ host.link }}">{{ host.basic_url }}</a>.
    {% endif %}
    </p>
  {% endif %}

  <code style="white-space: pre-wrap;">
{{ host.deploy_log }}
  </code>

  {% if host.status == HostStatus.error %}
    <p>Deploying this host failed. See the log above for more information.</p>
  {% elif host.status == HostStatus.destroying %}
    <p>This host is currently being destroyed.</p>
  {% elif host.status == HostStatus.defining %}
    <p>This host is not currently deployed to the cloud.</p>
  {% elif host.status != HostStatus.deploying %}
    <p>
    This host has been successfully deployed.
    {% if host.status == HostStatus.running %}
      You can view the live application at <a href="{{ host.link }}">{{ host.basic_url }}</a>.
    {% endif %}
    Or, return to your <a href="{{ url_for('main.index') }}">dashboard</a>.
    </p>
  {% endif %}
{% endblock content %}


{% block scripts %}
  {{ super() }}
  {# TODO: Refresh log using AJAX #}
{% endblock scripts %}

src/cloudlabs/templates/help.html
{% extends "base.html" %}


{% block breadcrumb_links %}
  {{ super() }}
  <li class="breadcrumb__item">Help</li>
{% endblock breadcrumb_links %}


{% block content %}
<h2>Welcome to CloudLabs!</h2>

<p>Our goal is to enable researchers to easily create virtual machines
(<em>"hosts"</em>) and other computational resources on which they can run code,
host web interfaces to their applications, and generally use for the
purposes of their research. These resources are created remotely ("<em>on the
cloud</em>"), without researchers needing to acquire dedicated physical
infrastructure.

<p>We have tried to keep the interface free of too much jargon and let users
achieve what they want without needing to know many details about cloud
computing. If you do want to learn some more, there are many resources online
about cloud computing; you may find this <a href="https://blogs.msdn.microsoft.com/azure_4_research/2016/10/18/cloud-computing-guide-for-researchers-faster-better-more-reproducible-research/">
article from Microsoft Azure</a> or
<a href="https://www.jisc.ac.uk/guides/cloud-computing-innovation-gdpr-and-you">
this overview</a> to be good starting points.

<p>Currently, the service uses Microsoft Azure as a cloud provider for the hosts
it creates.

<dl class="accordion">
  <dt class="accordion__title"><a href="#">Creating a new host</a>
  </dt>
  <dd class="accordion__description">
    <p>Once you are logged in, you can click the button to add a new host. This will
    first show you some information about limitations of the service, primarily
    related to privacy and personal data. <strong>Please take this information into
    account!</strong> If you agree that your use is suitable, you will be taken to
    a form where you can describe the resource that you would like to create.

    <p>Most of the fields in the form are self-explanatory (and you can see more
    detailed explanations if you hover on the information icon next to each field).
    However, the following comments may be useful:
    <ul>
      <li>
        The hosts created this way are accessible under the UCL domain. The actual URL
        will depend on the name you give in the form.
        For example, a host named <em>myhost</em> will be accessible at
        <em>myhost.cloudlabs.rc.ucl.ac.uk</em>
      </li>
      <li>
        You can choose to login to the host through either a username and password, or
        through SSH authentication. For the latter, you will first need to add your
        public key to your profile (click on your name from the top-right of any page).
      </li>
      <li>
        We assume that the code is in a git repository that is publically available
        (e.g. on GitHub, Bitbucket or a similar service). We also assume that there is
        a Dockerfile describing how the application should be launched. If either of
        these assumptions is not true, put in a random value in the appropriate field,
        and choose the option to customise the setup script. You will then be able to
        tailor the configuration of the host to your particular requirements.
      </li>
      <li>
        If your application needs on a specific port to be open, you can specify that
        in the form.
      </li>
    </ul>
    <p>A note about the setup script: Once the host has been created on the cloud,
    this service will connect to it and run various instructions, according to
    the information you have provided on the form. By default, this will try to
    clone a git repository, then run docker, exposing the specified port. If you
    want to change any aspect of that, select the "Customise setup script" button.
    From there, you will be able to add, modify or remove any of the instructions
    as required. Keep in mind that making this setup script more elaborate may
    incur a longer deployment time, especially if you have to install many
    requirements.

    <p>Once the host has been fully specified, it will take a few minutes to be created.
    You will be returned to the main page, from where you can track its progress.
  </dd>

  <dt class="accordion__title"><a href="#">The dashboard and controlling hosts</a>
  </dt>
  <dd class="accordion__description">
    <p>The dashboard on the <a href="{{ url_for('main.index') }}">main page</a>
    lists all hosts you have created, and lets you
    stop and restart them, edit their configuration and see information about them.
    You can also view information about hosts which are still being deployed by
    clicking on the "Deploying" status, which will display the host's log.

    <p>Hosts incur a charge while they are running, even if you are not actively
    using them. Once you no longer require a machine, think about stopping it. You
    can also delete hosts that you are no longer interested in, if you want to keep
    your dashboard cleaner.
  </dd>

  <dt class="accordion__title"><a href="#">Getting help</a>
  </dt>
  <dd class="accordion__description">
    <p>Note that <strong>the service is in active development!</strong> We are still
    adding features, and you may sometimes find that things are not fully working as
    expected. If you do notice something odd or encounter any problems, please let
    us know! We are also very interested in your feedback about the service, any
    changes you think are useful, and what features you would like to see added. You
    can <a href="mailto:rc-softdev@ucl.ac.uk">contact us by email</a> - don't
    hesitate to get in touch!
  </dd>

{% endblock content %}

src/cloudlabs/templates/host_info.html
{% extends "base.html" %}


{% block breadcrumb_links %}
  {{ super() }}
  <li class="breadcrumb__item">{{ host.label }}</li>
{% endblock breadcrumb_links %}


{% block content %}
  <h1>Information about host '{{ host.label }}'</h1>

  <dl>
    <dt>URL</dt>
    <dd><a href="{{ host.link }}">{{ host.basic_url }}</a></dd>
    <dt>Description</dt>
    <dd>{{ host.description }}</dd>
    <dt>Last started</dt>
    <dd>Unknown; TODO</dd>
    <dt>Cloud provider</dt>
    <dd>Microsoft Azure</dd>
    <dt>VM size</dt>
    <dd>{{ host.vm_type }}</dd>
    <dt>Operating System</dt>
    <dd>{{ host.os_info }}</dd>
    <dt>Disk type</dt>
    <dd>Unknown; TODO</dd>
    <dt>Disk size</dt>
    <dd>Unknown; TODO</dd>

    <dt>Authentication type</dt>
    <dd>
      {{ host.auth_type }}:
      {% if host.admin_ssh_key %}
        <a href="{{ url_for('main.profile') }}#key-{{ host.admin_ssh_key.id }}">{{ host.admin_ssh_key.label }}</a>
      {% else %}
        <a onclick="show_password(this)">click to show</a>
      {% endif %}
    </dd>
    {% if host.status != HostStatus.defining %}
    <dt>Deployment log</dt>
    <dd><a href="{{ url_for('host.view_log', id=host.id) }}">View deployment log</a></dd>
    {% endif %}
  </dl>
{% endblock content %}


{% block scripts %}
  {{ super() }}
  {# TODO: Put this in a static JS file loaded with require() and using jQuery #}
  <script>
    function show_password(elt) {
        var pw = document.createElement('span');
        pw.innerHTML = '{{ host.admin_password }}';
        elt.parentNode.replaceChild(pw, elt);
    }
  </script>
{% endblock scripts %}

src/cloudlabs/templates/index.html
{% extends "base.html" %}

{% block breadcrumb_links %}
  <li class="breadcrumb__item"><a href="https://www.ucl.ac.uk/">UCL Home</a></li>
  <li class="breadcrumb__item"><a href="http://www.ucl.ac.uk/research-it-services">Research IT Services</a></li>
  {% if user %}
    <li class="breadcrumb__item"><a href="{{ url_for('main.index') }}">Self-serve Web Hosting for Research Applications</a></li>
    <li class="breadcrumb__item">Dashboard</li>
  {% else %}
    <li class="breadcrumb__item">Self-serve Web Hosting for Research Applications</li>
  {% endif %}
{% endblock breadcrumb_links %}

{% block content %}
  <h1>Self-serve Web Hosting for Research Applications</h1>
  <p>Welcome to the trial 'CloudLabs' service for easy hosting of research web applications.</p>
  <p>You can find some general information about this service and how to use it on the
    <a href="{{ url_for('main.help') }}">help page</a>.
    In the future there will be more links to documentation about the service.</p>

  {% if user %}
    {% include "includes/_dashboard.html" %}
  {% else %}
    <p>You need to log in with your UCL credentials in order to use this service.</p>
    <a class="btn" href="{{ url_for('login') }}">Log in with UCL credentials</a>
  {% endif %}
{% endblock content %}


{% block scripts %}
  {{ super() }}
  {# TODO: Put this in a static JS file loaded with require() and using jQuery #}
  <script>
    function confirm_delete(url, action) {
        if (confirm('Are you sure you want to ' + action + ' this machine?'))
            document.location.href = url;
    }
  </script>
{% endblock scripts %}

src/cloudlabs/templates/login_error.html
{% extends "base.html" %}

{% block breadcrumb_links %}
  {{ super() }}
  <li class="breadcrumb__item">Self-serve Web Hosting for Research Applications</li>
{% endblock breadcrumb_links %}

{% block content %}
  <h1>Error processing Single-Sign-On</h1>
  <p>The identity provider has not given us sufficient information to identify you.</p>
  <p>Please contact rc-softdev@ucl.ac.uk to report this issue.</p>
  <h2>Technical information</h2>
  Shibboleth attributes received:
  <ul>
  {% for name, value in shib_attrs|dictsort %}
    <li>{{ name|e }} = {{ value|e }}</li>
  {% endfor %}
  </ul>
  Server environment:
  <ul>
  {% for name, value in request.environ|dictsort %}
    <li>{{ name|e }} = {{ value|e }}</li>
  {% endfor %}
  </ul>
{% endblock content %}

src/cloudlabs/templates/not_implemented.html
{% extends "base.html" %}


{% block breadcrumb_links %}
  {{ super() }}
  <li class="breadcrumb__item">{{ host.label }}</li>
{% endblock breadcrumb_links %}


{% block content %}
  <h1>Feature not yet implemented</h1>

  <p>{{ thing }} is not yet implemented.</p>

  <p>You can view <a href="{{ url_for('host.info', id=host.id) }}">information about this host</a>.</p>
{% endblock content %}

src/cloudlabs/templates/profile.html
{% extends "base.html" %}

{% block breadcrumb_links %}
  {{ super() }}
  <li class="breadcrumb__item">Profile</li>
{% endblock breadcrumb_links %}

{% block content %}
  <h1>User settings for {{ user['name'] }}</h1>
  <p>Here you can configure your SSH keys for logging in to deployed machines.</p>
  <p>In the future you will also be able to link CloudLabs to your GitHub account so you can deploy from private repositories.</p>
  <p>Visit the <a href="{{ url_for('main.index') }}">homepage</a> to view your existing machines or create new ones.</p>

  <a class="btn" href="{{ url_for('main.add_key') }}">Add new public key</a>

  {% if user.ssh_keys %}
  <p>
    Your existing public keys are shown below.
    Note that deleting a key from this list will not remove it from existing virtual machines &mdash;
    it will merely make it unavailable for selection when (re-)configuring a new or existing machine.
  </p>
  {% endif %}

  {% for key in user.ssh_keys %}
    <div class="box">
      <h4 id="key-{{ key.id }}">{{ key.label }}</h2>
      <p class="code">{{ key.public_key }}</p>
      <a href="{{ url_for('main.delete_key', id=key.id) }}"><img src="{{ url_for('static', filename='img/delete.svg') }}" alt="Delete SSH key" class="action" /></a>
    </div>
  {% endfor %}

{% endblock content %}

src/cloudlabs/templates/setup_script.html
{% extends "base.html" %}
{% from "includes/_form_helpers.html" import render_field %}

{% block content %}
  <form method="POST" action="{{ url_for('host.customise_setup') }}">
    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    {{ render_field(form.setup_script, rows=10) }}
    <input class="btn" type="submit" value="Add with customised setup script" />
  </form>
{% endblock content %}