src/cloudlabs/forms/add_host.py
from flask import g
from flask_wtf import FlaskForm
from wtforms.fields import (
    IntegerField,
    PasswordField,
    SelectField,
    StringField,
    TextAreaField
)
import wtforms.validators as v

from ..models import Host, SshKey


class AddHostForm(FlaskForm):
    """Form for adding a new virtual host."""

    label = StringField(
        'Label',
        description='A short label for you to identify this host easily',
        validators=[v.Length(min=2, max=Host.label.type.length)])

    description = TextAreaField(
        'Description',
        description='A longer description of the host, purely for your own '
                    'benefit',
        validators=[v.Optional()])

    base_name = StringField(
        'URL',
        description='The canonical DNS name for this host, which must be '
                    'globally unique. Note that the .cloudlabs.rc.ucl.ac.uk '
                    'suffix will be added automatically, and should not be '
                    'included here.',
        validators=[v.Length(min=1, max=Host.dns_name.type.length)])
    # TODO adapt max length to exclude suffixes/randomisation?

    vm_size = SelectField(
        'VM size',
        description='Specifications of new host',
        choices=[('Standard_A1_v2', '1 core, 2GB RAM'),
                 ('Standard_A4_v2', '4 cores, 8GB RAM'),
                 ('Standard_A4m_v2', '4 cores, 32GB RAM')])

    admin_username = StringField(
        'Admin username',
        description='Username of the admin user to be created on the new host',
        validators=[v.Length(min=1, max=Host.admin_username.type.length)])

    auth_type = SelectField(
        'Authentication type',
        description='How the admin user should be authenticated when logging '
                    'in via SSH',
        choices=[('SSH', 'SSH public key'), ('Password', 'Password')])

    admin_ssh_key = SelectField(
        'SSH public key',
        description='Which of your pre-configured SSH public keys to use for '
                    'logging in.'
        ' Set up further keys by visiting your profile page.',
        coerce=int)

    admin_password = PasswordField(
        'Admin password',
        description='Password to use for the admin user on this host',
        validators=[v.Optional(), v.Length(min=12,
                                           max=Host.admin_password.type.length
                                           )])

    git_repo = StringField(
        'Git repository',
        description='Location of the git repository to clone on the new host.'
        ' It is assumed to contain a Dockerfile that will be built,'
        ' although this can be customised.',
        validators=[v.Length(min=1, max=Host.git_repo.type.length)])

    port = IntegerField(
        'Port',
        description='Which port the web application should be exposed on.'
        ' This is used to generate our default installation script,'
        ' which can be customised if needed.',
        default=80,
        validators=[v.NumberRange(min=1, max=65535)])

    def validate_label(form, field):
        """Check a user doesn't duplicate labels."""
        label = field.data.strip()
        if Host.query.filter_by(user_id=g.user.id, label=label).count() > 0:
            raise v.ValidationError('You must choose a unique label for each '
                                    'host')

    def validate_dns_name(form, field):
        """DNS names must be globally unique."""
        dns_name = field.data.strip()
        if Host.query.filter_by(dns_name=dns_name).count() > 0:
            raise v.ValidationError('The URL {} has already '
                                    'been taken'.format(dns_name))

    def validate_admin_ssh_key(form, field):
        """The user must pick one of their keys."""
        key_id = field.data
        if key_id and SshKey.query.filter_by(user_id=g.user.id,
                                             id=key_id).count() == 0:
            raise v.ValidationError(
                        'You must select one of your pre-configured SSH keys')

src/cloudlabs/forms/add_key.py
from flask import g
from flask_wtf import FlaskForm
from wtforms.fields import StringField, TextAreaField
import wtforms.validators as v

from ..models import SshKey


class AddKeyForm(FlaskForm):
    """Form for adding a new SSH public key."""
    label = StringField(
        'Label',
        description='A label to allow you to identify this key',
        validators=[v.Length(min=2, max=SshKey.label.type.length)])
    public_key = TextAreaField(
        'Public key',
        description='The public key itself, e.g. copied from '
                    '~/.ssh/id_rsa.pub',
        validators=[v.DataRequired()])

    def validate_label(form, field):
        """Check a user doesn't duplicate labels."""
        existing_labels = [key.label for key in g.user.ssh_keys]
        if field.data.strip() in existing_labels:
            raise v.ValidationError(
                                'You must choose a unique label for each key')

src/cloudlabs/forms/customise_setup.py
from flask_wtf import FlaskForm
from wtforms.fields import TextAreaField, HiddenField
import wtforms.validators as v


class CustomiseSetupForm(FlaskForm):
    id = HiddenField()
    setup_script = TextAreaField('Setup script',
                                 description='Specify the (bash) script run'
                                             ' to initialise the new host',
                                 validators=[v.Optional()])

src/cloudlabs/views.py
import logging

from flask import (
    abort,
    Blueprint,
    flash,
    g,
    redirect,
    render_template,
    url_for,
)
from .forms.add_key import AddKeyForm
from .models import SshKey
from .utils import login_required


logger = logging.getLogger("cloudlabs.admin")

blueprint = Blueprint('main', __name__)


@blueprint.route('/')
def index():
    return render_template('index.html')


@blueprint.route('/profile')
@login_required
def profile():
    return render_template('profile.html')


@blueprint.route('/data_info')
def data_info():
    """Show a confirmation page with information on data-related limitations."""
    return render_template('data_info.html')


@blueprint.route('/help')
def help():
    """Show a help page with general information about CloudLabs."""
    return render_template('help.html')


@blueprint.route('/keys/add', methods=('GET', 'POST'))
@login_required
def add_key():
    form = AddKeyForm()
    if form.validate_on_submit():
        SshKey.create(
            user_id=g.user.id,
            label=form.label.data.strip(),
            public_key=form.public_key.data.strip())
        flash('SSH key "{}" added'.format(form.label.data), 'success')
        logger.info("%s added new key %s", g.user.ucl_id, form.label.data)
        return redirect(url_for('main.profile'))
    return render_template('add_key.html', form=form)


@blueprint.route('/keys/<int:id>/delete')
@login_required
def delete_key(id):
    key = SshKey.query.get_or_404(id)
    if key.user is not g.user:
        abort(404)
    label = key.label
    key.delete()
    logger.info("%s deleted key %s", g.user.ucl_id, label)
    flash('SSH key "{}" deleted'.format(label), 'success')
    return redirect(url_for('main.profile'))

src/cloudlabs/templates/includes/_dashboard.html
<!-- Listing of current user's machines -->

<p>
  This is your dashboard where you can see the list of machines you have created and their status,
  as well as stop/start them, make alterations to their configuration, download local copies, and create new machines.
</p>

{% if Roles.owner not in user.roles %}
<p>
  Note that in the alpha version of this service, only a small group of test users are able to create hosts. Contact the <a href="mailto:rc-softdev@ucl.ac.uk">Research Software Development Group</a> if you wish to join this group.
</p>
{% endif %}

<table class="hosts">
  <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Status</th>
      <th>Actions</th>
  </tr>
  {% for host in user.hosts %}
    <tr>
      <td><span title="{{ host.description }}">{{ host.label }}</span></td>
      <td><a href="{{ host.link }}">{{ host.basic_url }}</a></td>
      <td>
        {%- if host.status in [HostStatus.deploying, HostStatus.error, HostStatus.destroying] -%}
          <a href="{{ url_for('host.view_log', id=host.id) }}">
        {%- endif -%}
        {{ host.status.value }}
        {%- if host.status in [HostStatus.deploying, HostStatus.error, HostStatus.destroying] -%}
          </a>
        {%- endif -%}
      </td>
      <td>
        {% if host.status in [HostStatus.running, HostStatus.starting] %}
          <a href="{{ url_for('host.control', id=host.id, action='stop') }}"><img src="{{ url_for('static', filename='img/stop.svg') }}" alt="Stop virtual machine" title="Stop virtual machine" class="action" /></a>
        {% endif %}
        {% if host.status == HostStatus.running %}
          <a href="{{ url_for('host.control', id=host.id, action='restart') }}"><img src="{{ url_for('static', filename='img/restart.svg') }}" alt="Restart virtual machine" title="Restart virtual machine" class="action" /></a>
        {% endif %}
        {% if host.status == HostStatus.stopped %}
          <a href="{{ url_for('host.control', id=host.id, action='start') }}"><img src="{{ url_for('static', filename='img/start.svg') }}" alt="Start virtual machine" title="Start virtual machine" class="action" /></a>
        {% endif %}
        <a href="{{ url_for('host.edit', id=host.id) }}"><img src="{{ url_for('static', filename='img/configure.svg') }}" alt="Configure virtual machine" title="Configure virtual machine" class="action" /></a>
        <a href="{{ url_for('host.download', id=host.id) }}"><img src="{{ url_for('static', filename='img/download.svg') }}" alt="Download virtual machine image" title="Download virtual machine" class="action" /></a>
        <img src="{{ url_for('static', filename='img/delete.svg') }}" alt="Delete virtual machine" title="Delete virtual machine" class="action" onclick="confirm_delete('{{ url_for('host.delete', id=host.id) }}', '{{'delete' if host.status in [HostStatus.defining, HostStatus.error] else 'destroy'}}')" />
        <a href="{{ url_for('host.info', id=host.id) }}"><img src="{{ url_for('static', filename='img/info.svg') }}" alt="Show virtual machine info" title="Show virtual machine info" class="action" /></a>
      </td>
    </tr>
  {% endfor %}
</table>

{% if Roles.owner in user.roles %}
  <a class="btn" href="{{ url_for('main.data_info') }}">Add new host</a>
{% endif %}

{% if user.hosts.count() > 0 %}
  <p class="text-right small cite">
    Button icons designed by authors from Flaticon.
  </p>
{% endif %}

src/cloudlabs/templates/includes/_form_helpers.html
{% macro render_field(field) %}
  {{ field.label }}
  <img src="{{ url_for('static', filename='img/info.svg') }}" title="{{ field.description }}" class="inline" />
  {{ field(class='form__control', **kwargs)|safe }}
  {% if field.errors %}
    <ul class="error">
      {% for error in field.errors %}
        <li>{{ error }}</li>
      {% endfor %}
    </ul>
  {% endif %}
{% endmacro %}

src/cloudlabs/templates/includes/_login_state.html
<div class="login-state">
  {% if user %}
    Logged in as <a href="{{ url_for('main.profile') }}">{{ user['name'] }}</a>
    <a title="Log out" href="{{ url_for('logout') }}"><i class="fa fa-sign-out fa-r"></i></a>
  {% else %}
    <a href="{{ url_for('login') }}" class="btn positive-action login-button">
      <i class="fa fa-sign-in fa-l"></i> Log in with your UCL ID
    </a>
  {% endif %}
</div>

src/cloudlabs/templates/includes/_messages.html
{% with messages = get_flashed_messages(with_categories=True) %}
  {% if messages %}
    <ul class="message">
    {% for category, message in messages %}
      <li class="text-{{ category }}">{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}